import { useEffect, useMemo, useState } from "react";
import { api, download, json } from "../../api/client";
import type { AdminClub, AdminOverview, Administrator, BggDetails, ClubCollectionState, PeerTicket } from "../../api/types";
import { Badge, Card, Empty, ErrorState, Field, Loading, Notice, Page } from "../../components/Ui";
import { useAsync } from "../../hooks/useAsync";
import { telegram } from "../../telegram/webApp";

type Section = "communities" | "administrators" | "export" | "collection";

export function AdminPage() {
  const [section, setSection] = useState<Section>("communities"); const [clubId, setClubId] = useState<number>();
  useEffect(() => telegram.back(section === "collection", () => setSection("communities")), [section]);
  if (section === "collection" && clubId) return <ClubCollection clubId={clubId} back={() => setSection("communities")} />;
  return <><div className="admin-tabs"><button className={section === "communities" ? "active" : ""} onClick={() => setSection("communities")}>Сообщества</button><button className={section === "administrators" ? "active" : ""} onClick={() => setSection("administrators")}>Администраторы</button><button className={section === "export" ? "active" : ""} onClick={() => setSection("export")}>Экспорт</button></div>{section === "communities" ? <Communities manage={id => { setClubId(id); setSection("collection"); }} /> : section === "administrators" ? <Administrators /> : <Export />}</>;
}

function Communities({ manage }: { manage: (id: number) => void }) {
  const state = useAsync(() => api<AdminOverview>("/admin/overview"), []); const [create, setCreate] = useState<"club" | "camp">(); const [editing, setEditing] = useState<AdminClub>();
  if (create === "club") return <CreateClub done={() => { setCreate(undefined); state.reload(); }} />;
  if (create === "camp") return <CreateCamp overview={state.data} done={() => { setCreate(undefined); state.reload(); }} />;
  if (editing) return <EditClub club={editing} done={() => { setEditing(undefined); state.reload(); }} />;
  return <Page title="Сообщества" actions={<div className="row"><button onClick={() => setCreate("club")}>Новый клуб</button><button className="primary" onClick={() => setCreate("camp")}>Новый кэмп</button></div>}>
    {state.loading ? <Loading /> : state.error ? <ErrorState message={state.error} retry={state.reload} /> : <><h2>Клубы</h2>{!state.data?.clubs.length ? <Empty>Клубов пока нет.</Empty> : <div className="stack">{state.data.clubs.map(club => <Card key={club.id}><div className="row"><div><h3>{club.name}</h3><p className="muted">{club.telegramTitle} · {club.timeZoneId}</p><p>{club.gameCount} игр · ревизия {club.collectionRevision}</p></div><Badge tone={club.isActive ? "success" : "neutral"}>{club.isActive ? "Активен" : "Архив"}</Badge></div><div className="row"><button onClick={() => manage(club.id)}>Коллекция</button><button onClick={() => setEditing(club)}>Настройки</button></div></Card>)}</div>}<h2>Кэмпы</h2>{!state.data?.camps.length ? <Empty>Кэмпов пока нет.</Empty> : <div className="stack">{state.data.camps.map(camp => <Card key={camp.id}><div className="row"><div><h3>{camp.name}</h3><p>{camp.startDate} — {camp.endDate}</p><p className="muted">{camp.sourceClubName ? `Снимок: ${camp.sourceClubName}` : "Без исходного клуба"}</p><p>{camp.registrations} регистраций · {camp.contributions} игр · {camp.gatherings} сборов</p></div><Badge tone={camp.status === "Active" ? "success" : "neutral"}>{camp.status}</Badge></div><div className="row">{camp.status === "Draft" && <button className="primary" onClick={() => changeCamp(camp.id, "Active", state.reload)}>Активировать</button>}{camp.status === "Active" && <button onClick={() => changeCamp(camp.id, "Closed", state.reload)}>Закрыть</button>}{camp.status !== "Cancelled" && <button className="danger ghost" onClick={() => changeCamp(camp.id, "Cancelled", state.reload)}>Отменить</button>}</div></Card>)}</div>}</>}
  </Page>;
}

function EditClub({ club, done }: { club: AdminClub; done: () => void }) {
  const [name, setName] = useState(club.name); const [zone, setZone] = useState(club.timeZoneId); const [active, setActive] = useState(club.isActive); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  async function save() { if (!active && club.isActive && !await telegram.confirm("Архивировать клуб? Он исчезнет из выбора активных сообществ.")) return; setBusy(true); setError(undefined); try { await api(`/admin/clubs/${club.id}`, json("PUT", { name, timeZoneId: zone, isActive: active })); telegram.success(); done(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <Page title="Настройки клуба" actions={<button onClick={done}>Назад</button>}><Card className="form-grid"><Field label="Название"><input value={name} maxLength={160} onChange={e => setName(e.target.value)} /></Field><Field label="Часовой пояс"><input value={zone} onChange={e => setZone(e.target.value)} /></Field><label className="check"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} />Клуб активен</label>{error && <Notice kind="danger">{error}</Notice>}<button className="primary" disabled={busy || !name.trim() || !zone.trim()} onClick={save}>{busy ? "Сохраняем…" : "Сохранить"}</button></Card></Page>;
}

async function changeCamp(id: number, status: string, reload: () => void) { if (status === "Cancelled" && !await telegram.confirm("Отменить кэмп?")) return; await api(`/admin/camps/${id}/status`, json("POST", { status })); telegram.success(); reload(); }

function CreateClub({ done }: { done: () => void }) {
  const [name, setName] = useState(""); const [zone, setZone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  async function choose() { setBusy(true); setError(undefined); try { const selectionId = await selectPeer("CreateClubChat"); await api("/admin/clubs", json("POST", { selectionId, name, timeZoneId: zone })); telegram.success(); done(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <Page title="Новый клуб" actions={<button onClick={done}>Назад</button>}><Card><Field label="Название" hint="Если оставить пустым, используем название Telegram-группы"><input value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Часовой пояс"><input value={zone} onChange={e => setZone(e.target.value)} /></Field><Notice>Следующим шагом Telegram откроет штатный выбор группы. Бот и вы должны быть администраторами группы.</Notice>{error && <Notice kind="danger">{error}</Notice>}<button className="primary" disabled={busy || !zone} onClick={choose}>{busy ? "Ожидаем Telegram…" : "Выбрать группу"}</button></Card></Page>;
}

function CreateCamp({ overview, done }: { overview?: AdminOverview; done: () => void }) {
  const [name, setName] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [source, setSource] = useState<number | "">(""); const [zone, setZone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  async function choose() { if (!start || !end) { setError("Укажите даты кэмпа."); return; } setBusy(true); try { const selectionId = await selectPeer("CreateCampChat"); await api("/admin/camps", json("POST", { selectionId, name, startDate: start, endDate: end, sourceClubId: source || null, timeZoneId: zone })); telegram.success(); done(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <Page title="Новый кэмп" actions={<button onClick={done}>Назад</button>}><Card className="form-grid"><Field label="Название"><input value={name} onChange={e => setName(e.target.value)} /></Field><div className="limits"><Field label="Начало"><input type="date" value={start} onChange={e => setStart(e.target.value)} /></Field><Field label="Окончание"><input type="date" min={start} value={end} onChange={e => setEnd(e.target.value)} /></Field></div><Field label="Исходный клуб"><select value={source} onChange={e => setSource(e.target.value ? +e.target.value : "")}><option value="">Без базовой коллекции</option>{overview?.clubs.map(club => <option value={club.id} key={club.id}>{club.name}</option>)}</select></Field><Field label="Часовой пояс"><input value={zone} onChange={e => setZone(e.target.value)} /></Field>{source && <Notice>Коллекция клуба будет скопирована один раз. Будущие изменения клуба кэмп не изменят.</Notice>}{error && <Notice kind="danger">{error}</Notice>}<button className="primary" disabled={busy} onClick={choose}>{busy ? "Ожидаем Telegram…" : "Выбрать группу и проверить"}</button></Card></Page>;
}

function Administrators() {
  const state = useAsync(() => api<Administrator[]>("/admin/administrators"), []); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  async function add() { setBusy(true); setError(undefined); try { const selectionId = await selectPeer("AddAdministrator"); await api("/admin/administrators/from-selection", json("POST", { selectionId })); telegram.success(); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  async function remove(id: number) { if (!await telegram.confirm("Удалить администратора?")) return; try { await api(`/admin/administrators/${id}`, { method: "DELETE" }); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  return <Page title="Администраторы" actions={<button className="primary" disabled={busy} onClick={add}>Добавить администратора</button>}><Notice>Новый администратор должен открыть или запустить OyinQ перед использованием.</Notice>{error && <Notice kind="danger">{error}</Notice>}{state.loading ? <Loading /> : state.error ? <ErrorState message={state.error} retry={state.reload} /> : <div className="stack">{state.data?.map(admin => <Card key={admin.telegramUserId}><div className="row"><div><h3>{admin.displayName ?? "Пользователь Telegram"}</h3>{admin.telegramUsername && <p>@{admin.telegramUsername}</p>}<small className="muted">ID {admin.telegramUserId}</small></div><button className="danger ghost" onClick={() => remove(admin.telegramUserId)}>Удалить</button></div></Card>)}</div>}</Page>;
}

function Export() { const [error, setError] = useState<string>(); return <Page title="Экспорт и восстановление"><Card><h2>Статистика</h2><p>Скачать текущие сообщества, регистрации, вклады и сборы одним ZIP-файлом.</p><button onClick={() => download("/admin/exports/statistics.zip", "oyinq-statistics.zip").catch(e => setError(e.message))}>Скачать ZIP</button></Card><Notice>Коллекции клубов экспортируются отдельно на странице соответствующего клуба. Файл Roll-Move в репозитории — только аварийный снимок, а PostgreSQL остаётся источником истины.</Notice>{error && <Notice kind="danger">{error}</Notice>}</Page>; }

function ClubCollection({ clubId, back }: { clubId: number; back: () => void }) {
  const state = useAsync(() => api<ClubCollectionState>(`/admin/clubs/${clubId}/collection`), [clubId]); const [query, setQuery] = useState(""); const [input, setInput] = useState(""); const [preview, setPreview] = useState<BggDetails>(); const [searchResults, setSearchResults] = useState<{ bggId: number; name: string; yearPublished?: number }[]>([]); const [selectedExpansions, setSelectedExpansions] = useState<number[]>([]); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const games = useMemo(() => state.data?.collection.games.filter(g => g.name.toLowerCase().includes(query.toLowerCase())) ?? [], [state.data, query]);
  async function find() { setBusy(true); setError(undefined); try { setPreview(await api<BggDetails>(`/bgg/game?input=${encodeURIComponent(input)}`)); setSelectedExpansions([]); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  async function searchBgg() { setBusy(true); setError(undefined); try { setSearchResults(await api(`/bgg/search?query=${encodeURIComponent(input)}`)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  async function chooseBgg(id: number, expansionIds: number[] = []) { setBusy(true); setError(undefined); try { setInput(String(id)); setPreview(await api<BggDetails>(`/bgg/game?input=${id}`)); setSelectedExpansions(expansionIds); setSearchResults([]); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  async function add() { if (!state.data || !preview) return; setBusy(true); try { await api(`/admin/clubs/${clubId}/games`, json("POST", { expectedRevision: state.data.revision, bggInput: String(preview.game.bggId), expansionBggIds: selectedExpansions })); setInput(""); setPreview(undefined); setSelectedExpansions([]); telegram.success(); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); state.reload(); } finally { setBusy(false); } }
  async function remove(id: number, name: string) { if (!state.data || !await telegram.confirm(`Удалить «${name}» из коллекции?`)) return; try { await api(`/admin/clubs/${clubId}/games/${id}?expectedRevision=${state.data.revision}`, { method: "DELETE" }); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); state.reload(); } }
  async function importFile(file: File) { if (!state.data || !await telegram.confirm("Полностью заменить коллекцию содержимым файла?")) return; try { const document = JSON.parse(await file.text()); await api(`/admin/clubs/${clubId}/collection`, json("PUT", { expectedRevision: state.data.revision, document })); telegram.success(); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  return <Page title="Коллекция клуба" actions={<button onClick={back}>Назад</button>}>{state.loading ? <Loading /> : state.error || !state.data ? <ErrorState message={state.error ?? "Коллекция не найдена"} retry={state.reload} /> : <><div className="row"><Badge tone="accent">Ревизия {state.data.revision}</Badge><span className="muted">Обновлено {new Date(state.data.updatedAt).toLocaleString()}</span></div><Card><h2>Добавить игру</h2><Field label="Ссылка или название BGG"><input value={input} onChange={e => { setInput(e.target.value); setPreview(undefined); setSearchResults([]); }} /></Field><div className="row"><button disabled={busy || !input} onClick={find}>Открыть ссылку</button><button disabled={busy || input.trim().length < 2} onClick={searchBgg}>Найти по названию</button></div>{searchResults.length > 0 && <div className="stack">{searchResults.map(game => <button className="card community-option" key={game.bggId} onClick={() => chooseBgg(game.bggId)}><span><strong>{game.name}</strong><small>{game.yearPublished ?? "Год неизвестен"}</small></span></button>)}</div>}{preview && <div className="stack"><h3>{preview.game.name}</h3>{preview.expansions.length > 0 && <fieldset><legend>Дополнения в коллекции</legend>{preview.expansions.map(exp => <label className="check" key={exp.bggId}><input type="checkbox" checked={selectedExpansions.includes(exp.bggId)} onChange={() => setSelectedExpansions(current => current.includes(exp.bggId) ? current.filter(id => id !== exp.bggId) : [...current, exp.bggId])} />{exp.name}</label>)}</fieldset>}<button className="primary" disabled={busy} onClick={add}>Сохранить игру и дополнения</button></div>}</Card><Card><h2>Экспорт / восстановление</h2><div className="row"><button onClick={() => download(`/admin/clubs/${clubId}/collection/export`, `club-${clubId}.json`)}>Скачать JSON</button><label className="button">Импорт JSON<input hidden type="file" accept="application/json,.json" onChange={e => e.target.files?.[0] && importFile(e.target.files[0])} /></label></div></Card><Field label="Поиск по коллекции"><input value={query} onChange={e => setQuery(e.target.value)} /></Field>{error && <Notice kind="danger">{error}</Notice>}<div className="stack">{games.map(game => <Card key={game.bggId}><div className="row"><div><h3>{game.name}</h3>{game.expansions.length > 0 && <p className="muted">{game.expansions.map(x => x.name).join(", ")}</p>}</div><div className="row"><button onClick={() => chooseBgg(game.bggId, game.expansions.map(x => x.bggId))}>Дополнения</button><button className="danger ghost" onClick={() => remove(game.bggId, game.name)}>Удалить</button></div></div></Card>)}</div></>}</Page>;
}

async function selectPeer(purpose: "AddAdministrator" | "CreateClubChat" | "CreateCampChat"): Promise<string> {
  const ticket = await api<PeerTicket>("/admin/peer-selections", json("POST", { purpose }));
  const opened = ticket.preparedButtonId ? await telegram.requestPeer(ticket.preparedButtonId) : false;
  if (!opened) await api(`/admin/peer-selections/${ticket.publicId}/fallback`, { method: "POST" });
  for (let attempt = 0; attempt < 100; attempt++) {
    await new Promise(resolve => setTimeout(resolve, 1500));
    const current = await api<PeerTicket>(`/admin/peer-selections/${ticket.publicId}`);
    if (current.status === "Completed" || current.status === "Consumed") return current.publicId;
    if (current.status === "Expired") throw new Error("Запрос выбора Telegram истёк.");
  }
  throw new Error("Telegram не вернул выбранный объект.");
}
