// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using oyinQ.Bot.Data;

#nullable disable

namespace oyinQ.Bot.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904131050_WishlistAndRecruitment")]
    partial class WishlistAndRecruitment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Camp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseCollectionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BotChatKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("BotChatMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long?>("SourceClubId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotChatKey")
                        .IsUnique();

                    b.HasIndex("SourceClubId");

                    b.HasIndex("BotChatKey", "BotChatMode")
                        .IsUnique();

                    b.HasIndex("Status", "EndsAtUtc", "Id");

                    b.ToTable("Camps", null, t =>
                        {
                            t.HasCheckConstraint("CK_Camps_BotChatMode", "\"BotChatMode\" = 1");

                            t.HasCheckConstraint("CK_Camps_OperatingWindow", "(\"StartsAtUtc\" IS NULL AND \"EndsAtUtc\" IS NULL) OR (\"StartsAtUtc\" IS NOT NULL AND \"EndsAtUtc\" IS NOT NULL AND \"StartsAtUtc\" < \"EndsAtUtc\")");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampBggImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("BggUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("CampId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmationJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OverrideResolution")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OverrideResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_CampBggImports_ActiveProfileParticipant")
                        .HasFilter("\"CampId\" IS NULL AND \"Status\" IN (0, 1)");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("CampId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_CampBggImports_ActiveCampParticipant")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("CampId", "ParticipantId", "UpdatedAt");

                    b.HasIndex("Status", "LeaseExpiresAt", "CreatedAt");

                    b.ToTable("CampBggImports", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampGameContribution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BggId")
                        .HasColumnType("bigint");

                    b.Property<long>("CampId")
                        .HasColumnType("bigint");

                    b.Property<int>("Commitment")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentBggId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CampId", "BggId", "ItemType");

                    b.HasIndex("CampId", "ParticipantId", "BggId", "ItemType")
                        .IsUnique();

                    b.ToTable("CampGameContributions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CampId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DaysStaying")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("NeedsAccommodation")
                        .HasColumnType("boolean");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CampId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("CampRegistrations", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistrationDay", b =>
                {
                    b.Property<long>("CampRegistrationId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("CampRegistrationId", "Date");

                    b.ToTable("CampRegistrationDays", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ChatAdminPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommunityKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("GrantedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityKey", "RevokedAt");

                    b.HasIndex("TelegramUserId", "CommunityKey")
                        .IsUnique();

                    b.ToTable("ChatAdminPermissions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Club", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BotChatKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("BotChatMode")
                        .HasColumnType("integer");

                    b.Property<string>("CollectionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("CollectionRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotChatKey")
                        .IsUnique();

                    b.HasIndex("BotChatKey", "BotChatMode")
                        .IsUnique();

                    b.ToTable("Clubs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clubs_BotChatMode", "\"BotChatMode\" = 0");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubBggImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AddedExpansions")
                        .HasColumnType("integer");

                    b.Property<int>("AddedGames")
                        .HasColumnType("integer");

                    b.Property<string>("BggUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrphanExpansions")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClubBggImports_ActiveClub")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAt", "CreatedAt");

                    b.ToTable("ClubBggImports", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubMetadataRefresh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BggIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClubMetadataRefreshes_ActiveClub")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAt", "CreatedAt");

                    b.ToTable("ClubMetadataRefreshes", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGathering", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanTeachRules")
                        .HasColumnType("boolean");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommunityKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("ConfirmedWasPlayed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DesiredPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("GameSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("LastPublicationAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegacyPlayOutcomeJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("MaximumPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumPlayers")
                        .HasColumnType("integer");

                    b.Property<long>("OrganizerParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("OutcomeRecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OutcomeRecordedByParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("OutcomeRevision")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("PublicationAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PublicationError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PublicationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerParticipantId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("CommunityKey", "StartsAtUtc");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .IsUnique();

                    b.HasIndex("Status", "StartsAtUtc", "Id");

                    b.ToTable("GameGatherings", null, t =>
                        {
                            t.HasCheckConstraint("CK_GameGatherings_PlayerLimits", "\"MinimumPlayers\" >= 1 AND \"MinimumPlayers\" <= \"DesiredPlayers\" AND \"DesiredPlayers\" <= \"MaximumPlayers\"");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringExpansion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BggId")
                        .HasColumnType("bigint");

                    b.Property<long>("GameGatheringId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("GameGatheringId", "BggId")
                        .IsUnique();

                    b.ToTable("GameGatheringExpansions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringGuest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("GameGatheringId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByParticipantId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("GameGatheringId", "Id");

                    b.ToTable("GameGatheringGuests", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttendanceOutcome")
                        .HasColumnType("integer");

                    b.Property<long>("GameGatheringId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("GameGatheringId", "ParticipantId")
                        .IsUnique();

                    b.HasIndex("GameGatheringId", "Status", "JoinedAt");

                    b.ToTable("GameGatheringParticipants", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameWish", b =>
                {
                    b.Property<string>("CommunityKey")
                        .HasColumnType("character varying(32)");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<long>("BggId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("CommunityKey", "ParticipantId", "BggId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CommunityKey", "BggId");

                    b.ToTable("GameWishes", t =>
                        {
                            t.HasCheckConstraint("CK_GameWish_BggId", "\"BggId\" > 0");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GatheringExternalPlayReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddedByParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GatheringPlayRecordId")
                        .HasColumnType("bigint");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByParticipantId");

                    b.HasIndex("GatheringPlayRecordId", "Url")
                        .IsUnique();

                    b.ToTable("GatheringExternalPlayReferences");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GatheringPlayPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayRecordId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourcePlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("PlayRecordId", "SourcePlayerId")
                        .IsUnique();

                    b.ToTable("GatheringPlayPlayers");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GatheringPlayRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("GameSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("GatheringId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RecordedByParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasPlayed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GatheringId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RecordedByParticipantId");

                    b.ToTable("GatheringPlayRecords", t =>
                        {
                            t.HasCheckConstraint("CK_PlayRecord_Outcome", "(\"WasPlayed\" AND \"EndedAtUtc\" IS NOT NULL) OR (NOT \"WasPlayed\" AND \"EndedAtUtc\" IS NULL)");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.KnownTelegramChat", b =>
                {
                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBotPresent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForum")
                        .HasColumnType("boolean");

                    b.Property<string>("TelegramPhotoFileId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("TelegramPhotoUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TelegramChatId");

                    b.HasIndex("IsBotPresent");

                    b.ToTable("KnownTelegramChats", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CommunityKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GatheringPublicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImportPublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("ParticipantId");

                    b.HasIndex("GatheringPublicId", "ParticipantId");

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.NotificationPreferences", b =>
                {
                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<bool>("GatheringDetailsChanged")
                        .HasColumnType("boolean");

                    b.Property<bool>("GatheringFull")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImportCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrganizerBelowMinimum")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrganizerMissingProvider")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrganizerParticipantLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrganizerReplacement")
                        .HasColumnType("boolean");

                    b.Property<int>("ReminderLeadMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("WishlistGathering")
                        .HasColumnType("boolean");

                    b.HasKey("ParticipantId");

                    b.ToTable("NotificationPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationPreferences_Reminder", "\"ReminderLeadMinutes\" IN (0, 30, 60, 120, 360, 720, 1440)");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.OyinQCommunity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRecruitmentDigestAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("PostingMessageThreadId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PostingTopicInvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecruitmentCooldownHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("OyinQCommunities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Community_RecruitmentCooldown", "\"RecruitmentCooldownHours\" BETWEEN 1 AND 24");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Participant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveCommunityKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PreferredDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("PrivateChatStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("TelegramDeliveryBlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ParticipantCollectionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BggId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentBggId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "BggId", "ItemType")
                        .IsUnique();

                    b.ToTable("ParticipantCollectionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ParticipantCollectionItems_BggId", "\"BggId\" > 0");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.PendingTelegramPeerSelection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreparedButtonId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<long>("RequestedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("RequestedByTelegramUserId", "Status", "ExpiresAt");

                    b.ToTable("PendingTelegramPeerSelections", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.RecruitmentDigest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommunityKey")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommunityKey")
                        .IsUnique()
                        .HasFilter("\"State\" IN (0, 1, 2)");

                    b.HasIndex("State", "RequestedAt");

                    b.ToTable("RecruitmentDigests");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ReleaseAnnouncement", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("character varying(3500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByParticipantId");

                    b.ToTable("ReleaseAnnouncements");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ReleaseAnnouncementDelivery", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CommunityKey")
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.HasKey("ReleaseId", "CommunityKey");

                    b.HasIndex("CommunityKey");

                    b.HasIndex("State", "AttemptedAt");

                    b.ToTable("ReleaseAnnouncementDeliveries");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.TelegramForumTopic", b =>
                {
                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageThreadId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TelegramChatId", "MessageThreadId");

                    b.HasIndex("TelegramChatId", "IsDeleted", "IsClosed");

                    b.ToTable("TelegramForumTopics", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.TelegramMessageCleanup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LastAttemptAt", "CreatedAt");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .IsUnique();

                    b.ToTable("TelegramMessageCleanups", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Camp", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Club", "SourceClub")
                        .WithMany("SourceCamps")
                        .HasForeignKey("SourceClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "BotChat")
                        .WithOne("Camp")
                        .HasForeignKey("oyinQ.Bot.Data.Entities.Camp", "BotChatKey", "BotChatMode")
                        .HasPrincipalKey("oyinQ.Bot.Data.Entities.OyinQCommunity", "Key", "Mode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BotChat");

                    b.Navigation("SourceClub");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampBggImport", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Camp", "Camp")
                        .WithMany("BggImports")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampGameContribution", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Camp", "Camp")
                        .WithMany("Contributions")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("CampGameContributions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistration", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Camp", "Camp")
                        .WithMany("Registrations")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("CampRegistrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistrationDay", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.CampRegistration", "CampRegistration")
                        .WithMany("SelectedDays")
                        .HasForeignKey("CampRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampRegistration");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ChatAdminPermission", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "Community")
                        .WithMany("AdminPermissions")
                        .HasForeignKey("CommunityKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Club", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "BotChat")
                        .WithOne("Club")
                        .HasForeignKey("oyinQ.Bot.Data.Entities.Club", "BotChatKey", "BotChatMode")
                        .HasPrincipalKey("oyinQ.Bot.Data.Entities.OyinQCommunity", "Key", "Mode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BotChat");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubBggImport", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubMetadataRefresh", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGathering", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "Community")
                        .WithMany("Gatherings")
                        .HasForeignKey("CommunityKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "OrganizerParticipant")
                        .WithMany("OrganizedGatherings")
                        .HasForeignKey("OrganizerParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("OrganizerParticipant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringExpansion", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.GameGathering", "GameGathering")
                        .WithMany("Expansions")
                        .HasForeignKey("GameGatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameGathering");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringGuest", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "CreatedByParticipant")
                        .WithMany("CreatedGatheringGuests")
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.GameGathering", "GameGathering")
                        .WithMany("Guests")
                        .HasForeignKey("GameGatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByParticipant");

                    b.Navigation("GameGathering");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringParticipant", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.GameGathering", "GameGathering")
                        .WithMany("Participants")
                        .HasForeignKey("GameGatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("GatheringParticipations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameGathering");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameWish", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GatheringExternalPlayReference", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "AddedByParticipant")
                        .WithMany()
                        .HasForeignKey("AddedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.GatheringPlayRecord", "PlayRecord")
                        .WithMany()
                        .HasForeignKey("GatheringPlayRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByParticipant");

                    b.Navigation("PlayRecord");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GatheringPlayPlayer", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("oyinQ.Bot.Data.Entities.GatheringPlayRecord", "PlayRecord")
                        .WithMany("Players")
                        .HasForeignKey("PlayRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("PlayRecord");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GatheringPlayRecord", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.GameGathering", "Gathering")
                        .WithOne()
                        .HasForeignKey("oyinQ.Bot.Data.Entities.GatheringPlayRecord", "GatheringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "RecordedByParticipant")
                        .WithMany()
                        .HasForeignKey("RecordedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gathering");

                    b.Navigation("RecordedByParticipant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Notification", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.NotificationPreferences", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithOne()
                        .HasForeignKey("oyinQ.Bot.Data.Entities.NotificationPreferences", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ParticipantCollectionItem", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.RecruitmentDigest", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ReleaseAnnouncement", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", null)
                        .WithMany()
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ReleaseAnnouncementDelivery", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.ReleaseAnnouncement", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.TelegramForumTopic", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.KnownTelegramChat", null)
                        .WithMany()
                        .HasForeignKey("TelegramChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Camp", b =>
                {
                    b.Navigation("BggImports");

                    b.Navigation("Contributions");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistration", b =>
                {
                    b.Navigation("SelectedDays");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Club", b =>
                {
                    b.Navigation("SourceCamps");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGathering", b =>
                {
                    b.Navigation("Expansions");

                    b.Navigation("Guests");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GatheringPlayRecord", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.OyinQCommunity", b =>
                {
                    b.Navigation("AdminPermissions");

                    b.Navigation("Camp");

                    b.Navigation("Club");

                    b.Navigation("Gatherings");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Participant", b =>
                {
                    b.Navigation("CampGameContributions");

                    b.Navigation("CampRegistrations");

                    b.Navigation("CreatedGatheringGuests");

                    b.Navigation("GatheringParticipations");

                    b.Navigation("OrganizedGatherings");
                });
#pragma warning restore 612, 618
        }
    }
}
