// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using oyinQ.Bot.Data;

#nullable disable

namespace oyinQ.Bot.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828155134_AddParticipantCommunityContext")]
    partial class AddParticipantCommunityContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CollectionImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AddedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalUsername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgressJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<long>("RequestedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RequestedByTelegramUserId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Provider", "ExternalUsername", "ParticipantId", "Target", "Status");

                    b.ToTable("CollectionImports", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BestPlayers")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("BggId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TeseraAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BggId")
                        .IsUnique();

                    b.HasIndex("NormalizedName");

                    b.HasIndex("TeseraAlias")
                        .IsUnique();

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameCopy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BringStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OwnerParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("IX_GameCopies_GameId_Club")
                        .HasFilter("\"OwnerParticipantId\" IS NULL AND \"Source\" = 1");

                    b.HasIndex("OwnerParticipantId");

                    b.HasIndex("GameId", "OwnerParticipantId")
                        .IsUnique();

                    b.ToTable("GameCopies", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameInterest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParticipantId", "GameId")
                        .IsUnique();

                    b.ToTable("GameInterests", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("HostParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WantedAdditionalPlayers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("HostParticipantId");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .IsUnique();

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSessionParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameSessionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("GameSessionId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("GameSessionParticipants", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Participant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveCommunityKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DaysStaying")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool?>("NeedsAccommodation")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ParticipantConversationState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("ParticipantConversationStates", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CollectionImport", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("CollectionImports")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameCopy", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Game", "Game")
                        .WithMany("Copies")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "OwnerParticipant")
                        .WithMany("GameCopies")
                        .HasForeignKey("OwnerParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("OwnerParticipant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameInterest", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Game", "Game")
                        .WithMany("Interests")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("GameInterests")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSession", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "HostParticipant")
                        .WithMany("HostedGameSessions")
                        .HasForeignKey("HostParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("HostParticipant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSessionParticipant", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.GameSession", "GameSession")
                        .WithMany("Participants")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("GameSessionParticipations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ParticipantConversationState", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithOne("ConversationState")
                        .HasForeignKey("oyinQ.Bot.Data.Entities.ParticipantConversationState", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Game", b =>
                {
                    b.Navigation("Copies");

                    b.Navigation("Interests");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Participant", b =>
                {
                    b.Navigation("CollectionImports");

                    b.Navigation("ConversationState");

                    b.Navigation("GameCopies");

                    b.Navigation("GameInterests");

                    b.Navigation("GameSessionParticipations");

                    b.Navigation("HostedGameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
