// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using oyinQ.Bot.Data;

#nullable disable

namespace oyinQ.Bot.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901053106_ChatScopedAdministration")]
    partial class ChatScopedAdministration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Camp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseCollectionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BotChatKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("BotChatMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long?>("SourceClubId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotChatKey")
                        .IsUnique();

                    b.HasIndex("SourceClubId");

                    b.HasIndex("BotChatKey", "BotChatMode")
                        .IsUnique();

                    b.HasIndex("Status", "EndDate", "Id");

                    b.ToTable("Camps", null, t =>
                        {
                            t.HasCheckConstraint("CK_Camps_BotChatMode", "\"BotChatMode\" = 1");

                            t.HasCheckConstraint("CK_Camps_DateRange", "(\"StartDate\" IS NULL AND \"EndDate\" IS NULL) OR (\"StartDate\" IS NOT NULL AND \"EndDate\" IS NOT NULL AND \"StartDate\" <= \"EndDate\")");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampBggImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("BggUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("CampId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmationJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OverrideResolution")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OverrideResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("CampId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_CampBggImports_ActiveCampParticipant")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("CampId", "ParticipantId", "UpdatedAt");

                    b.HasIndex("Status", "LeaseExpiresAt", "CreatedAt");

                    b.ToTable("CampBggImports", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampGameContribution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BggId")
                        .HasColumnType("bigint");

                    b.Property<long>("CampId")
                        .HasColumnType("bigint");

                    b.Property<int>("Commitment")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentBggId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CampId", "BggId", "ItemType");

                    b.HasIndex("CampId", "ParticipantId", "BggId", "ItemType")
                        .IsUnique();

                    b.ToTable("CampGameContributions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CampId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DaysStaying")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("NeedsAccommodation")
                        .HasColumnType("boolean");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CampId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("CampRegistrations", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistrationDay", b =>
                {
                    b.Property<long>("CampRegistrationId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("CampRegistrationId", "Date");

                    b.ToTable("CampRegistrationDays", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ChatAdminPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommunityKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("GrantedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityKey", "RevokedAt");

                    b.HasIndex("TelegramUserId", "CommunityKey")
                        .IsUnique();

                    b.ToTable("ChatAdminPermissions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Club", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BggUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BotChatKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("BotChatMode")
                        .HasColumnType("integer");

                    b.Property<string>("CollectionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("CollectionRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotChatKey")
                        .IsUnique();

                    b.HasIndex("BotChatKey", "BotChatMode")
                        .IsUnique();

                    b.ToTable("Clubs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clubs_BotChatMode", "\"BotChatMode\" = 0");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubBggImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AddedExpansions")
                        .HasColumnType("integer");

                    b.Property<int>("AddedGames")
                        .HasColumnType("integer");

                    b.Property<string>("BggUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrphanExpansions")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClubBggImports_ActiveClub")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAt", "CreatedAt");

                    b.ToTable("ClubBggImports", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubMetadataRefresh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BggIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClubMetadataRefreshes_ActiveClub")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAt", "CreatedAt");

                    b.ToTable("ClubMetadataRefreshes", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CollectionImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AddedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalUsername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgressJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<long>("RequestedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RequestedByTelegramUserId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Provider", "ExternalUsername", "ParticipantId", "Target", "Status");

                    b.ToTable("CollectionImports", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BestPlayers")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("BggId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BggId")
                        .IsUnique();

                    b.HasIndex("NormalizedName");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameCopy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BringStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OwnerParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("IX_GameCopies_GameId_Club")
                        .HasFilter("\"OwnerParticipantId\" IS NULL AND \"Source\" = 1");

                    b.HasIndex("OwnerParticipantId");

                    b.HasIndex("GameId", "OwnerParticipantId")
                        .IsUnique();

                    b.ToTable("GameCopies", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGathering", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanTeachRules")
                        .HasColumnType("boolean");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommunityKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DesiredPlayers")
                        .HasColumnType("integer");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("LastPublicationAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaximumPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumPlayers")
                        .HasColumnType("integer");

                    b.Property<long>("OrganizerParticipantId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("PublicationAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PublicationError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PublicationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrganizerParticipantId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("CommunityKey", "StartsAtUtc");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .IsUnique();

                    b.HasIndex("Status", "StartsAtUtc", "Id");

                    b.ToTable("GameGatherings", null, t =>
                        {
                            t.HasCheckConstraint("CK_GameGatherings_PlayerLimits", "\"MinimumPlayers\" >= 1 AND \"MinimumPlayers\" <= \"DesiredPlayers\" AND \"DesiredPlayers\" <= \"MaximumPlayers\"");
                        });
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringExpansion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BggId")
                        .HasColumnType("bigint");

                    b.Property<long>("GameGatheringId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("GameGatheringId", "BggId")
                        .IsUnique();

                    b.ToTable("GameGatheringExpansions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttendanceOutcome")
                        .HasColumnType("integer");

                    b.Property<long>("GameGatheringId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("GameGatheringId", "ParticipantId")
                        .IsUnique();

                    b.HasIndex("GameGatheringId", "Status", "JoinedAt");

                    b.ToTable("GameGatheringParticipants", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameInterest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParticipantId", "GameId")
                        .IsUnique();

                    b.ToTable("GameInterests", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("HostParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WantedAdditionalPlayers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("HostParticipantId");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .IsUnique();

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSessionParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameSessionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("GameSessionId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("GameSessionParticipants", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.OyinQAdministrator", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TelegramUserId");

                    b.ToTable("OyinQAdministrators", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.OyinQCommunity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.HasIndex("TelegramChatId")
                        .IsUnique();

                    b.ToTable("OyinQCommunities", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Participant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveCommunityKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DaysStaying")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool?>("NeedsAccommodation")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ParticipantConversationState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("ParticipantConversationStates", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.PendingTelegramPeerSelection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreparedButtonId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<long>("RequestedByTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("RequestedByTelegramUserId", "Status", "ExpiresAt");

                    b.ToTable("PendingTelegramPeerSelections", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.TelegramMessageCleanup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LastAttemptAt", "CreatedAt");

                    b.HasIndex("TelegramChatId", "TelegramMessageId")
                        .IsUnique();

                    b.ToTable("TelegramMessageCleanups", (string)null);
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Camp", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Club", "SourceClub")
                        .WithMany("SourceCamps")
                        .HasForeignKey("SourceClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "BotChat")
                        .WithOne("Camp")
                        .HasForeignKey("oyinQ.Bot.Data.Entities.Camp", "BotChatKey", "BotChatMode")
                        .HasPrincipalKey("oyinQ.Bot.Data.Entities.OyinQCommunity", "Key", "Mode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BotChat");

                    b.Navigation("SourceClub");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampBggImport", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Camp", "Camp")
                        .WithMany("BggImports")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampGameContribution", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Camp", "Camp")
                        .WithMany("Contributions")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("CampGameContributions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistration", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Camp", "Camp")
                        .WithMany("Registrations")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("CampRegistrations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistrationDay", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.CampRegistration", "CampRegistration")
                        .WithMany("SelectedDays")
                        .HasForeignKey("CampRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampRegistration");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ChatAdminPermission", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "Community")
                        .WithMany("AdminPermissions")
                        .HasForeignKey("CommunityKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Club", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "BotChat")
                        .WithOne("Club")
                        .HasForeignKey("oyinQ.Bot.Data.Entities.Club", "BotChatKey", "BotChatMode")
                        .HasPrincipalKey("oyinQ.Bot.Data.Entities.OyinQCommunity", "Key", "Mode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BotChat");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubBggImport", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ClubMetadataRefresh", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CollectionImport", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("CollectionImports")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameCopy", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Game", "Game")
                        .WithMany("Copies")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "OwnerParticipant")
                        .WithMany("GameCopies")
                        .HasForeignKey("OwnerParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("OwnerParticipant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGathering", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.OyinQCommunity", "Community")
                        .WithMany("Gatherings")
                        .HasForeignKey("CommunityKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Game", "Game")
                        .WithMany("Gatherings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "OrganizerParticipant")
                        .WithMany("OrganizedGatherings")
                        .HasForeignKey("OrganizerParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Game");

                    b.Navigation("OrganizerParticipant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringExpansion", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.GameGathering", "GameGathering")
                        .WithMany("Expansions")
                        .HasForeignKey("GameGatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameGathering");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGatheringParticipant", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.GameGathering", "GameGathering")
                        .WithMany("Participants")
                        .HasForeignKey("GameGatheringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("GatheringParticipations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameGathering");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameInterest", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Game", "Game")
                        .WithMany("Interests")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("GameInterests")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSession", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "HostParticipant")
                        .WithMany("HostedGameSessions")
                        .HasForeignKey("HostParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("HostParticipant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSessionParticipant", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.GameSession", "GameSession")
                        .WithMany("Participants")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithMany("GameSessionParticipations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.ParticipantConversationState", b =>
                {
                    b.HasOne("oyinQ.Bot.Data.Entities.Participant", "Participant")
                        .WithOne("ConversationState")
                        .HasForeignKey("oyinQ.Bot.Data.Entities.ParticipantConversationState", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Camp", b =>
                {
                    b.Navigation("BggImports");

                    b.Navigation("Contributions");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.CampRegistration", b =>
                {
                    b.Navigation("SelectedDays");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Club", b =>
                {
                    b.Navigation("SourceCamps");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Game", b =>
                {
                    b.Navigation("Copies");

                    b.Navigation("Gatherings");

                    b.Navigation("Interests");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameGathering", b =>
                {
                    b.Navigation("Expansions");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.GameSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.OyinQCommunity", b =>
                {
                    b.Navigation("AdminPermissions");

                    b.Navigation("Camp");

                    b.Navigation("Club");

                    b.Navigation("Gatherings");
                });

            modelBuilder.Entity("oyinQ.Bot.Data.Entities.Participant", b =>
                {
                    b.Navigation("CampGameContributions");

                    b.Navigation("CampRegistrations");

                    b.Navigation("CollectionImports");

                    b.Navigation("ConversationState");

                    b.Navigation("GameCopies");

                    b.Navigation("GameInterests");

                    b.Navigation("GameSessionParticipations");

                    b.Navigation("GatheringParticipations");

                    b.Navigation("HostedGameSessions");

                    b.Navigation("OrganizedGatherings");
                });
#pragma warning restore 612, 618
        }
    }
}
