import { type ReactNode, useEffect, useMemo, useState } from "react";
import { ApiError, api, json } from "../../api/client";
import type { CampImport, ClubGame, Community, Contribution, ImportDraftItem } from "../../api/types";
import { Badge, Card, Cover, Empty, ErrorState, Field, Loading, Notice, Page } from "../../components/Ui";
import { GameMeta, GamePicker, searchGames } from "../../components/GamePicker";
import { useAsync } from "../../hooks/useAsync";
import { telegram } from "../../telegram/webApp";
import { formatDate } from "../../app/format";
import { defaultImportSelection, importItemKey, isImportItemSelectable } from "./importSelection";

type RegistrationState = { campStatus: string; startDate?: string; endDate?: string; availableDates: string[]; baseGameIds: number[]; registration?: { registered: boolean; daysStaying: number; selectedDates: string[]; suggestedDates: string[]; needsAccommodation: boolean; city?: string; displayName?: string } };

export function MyGamesPage({ community, bggAvailable, editRequest = 0 }: { community: Community; bggAvailable: boolean; editRequest?: number }) {
  const [editingRegistration, setEditingRegistration] = useState(false);
  const registration = useAsync(() => api<RegistrationState>(`/camp/registration?community=${encodeURIComponent(community.key)}`), [community.key]);
  useEffect(() => { if (editRequest > 0) setEditingRegistration(true); }, [editRequest]);
  if (editingRegistration) return registration.error ? <Page title="Регистрация на кэмп" actions={<button onClick={() => setEditingRegistration(false)}>Назад</button>}><ErrorState message={registration.error} retry={registration.reload} /></Page> : registration.data ? <Registration community={community} state={registration.data} done={() => { registration.reload(); setEditingRegistration(false); }} cancel={() => setEditingRegistration(false)} /> : <Page title="Регистрация на кэмп"><Loading /></Page>;
  return <Contributions community={community} bggAvailable={bggAvailable} registration={registration.data} editRegistration={() => setEditingRegistration(true)} />;
}

export function CampRegistrationGate({ community, isAdministrator, children }: { community: Community; isAdministrator: boolean; children: ReactNode }) {
  const registration = useAsync(() => api<RegistrationState>(`/camp/registration?community=${encodeURIComponent(community.key)}`), [community.key]);
  if (registration.loading) return <Page title="Кэмп"><Loading /></Page>;
  if (registration.error) return <Page title="Кэмп"><ErrorState message={registration.error} retry={registration.reload} /></Page>;
  if (!registration.data?.startDate || !registration.data.endDate) return <Page title="Кэмп ещё настраивается" subtitle={community.name}><Notice kind="warning">Организатор ещё не указал даты кэмпа. Регистрация и создание сборов станут доступны после настройки.</Notice>{isAdministrator && <a className="button primary-link" href="?admin=1">Указать даты в админ-панели</a>}</Page>;
  if (!registration.data.registration?.registered) return <Registration community={community} state={registration.data} done={registration.reload} />;
  return <>{children}</>;
}

function Registration({ community, state, done, cancel }: { community: Community; state: RegistrationState; done: () => void; cancel?: () => void }) {
  const initialDates = state.registration?.selectedDates?.length ? state.registration.selectedDates : state.registration?.suggestedDates ?? [];
  const [selectedDates, setSelectedDates] = useState<string[]>(initialDates); const [housing, setHousing] = useState(state.registration?.needsAccommodation ?? false); const [name, setName] = useState(state.registration?.displayName ?? ""); const [city, setCity] = useState(state.registration?.city ?? ""); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  async function save(confirmAttendanceChanges = false) { await api("/camp/registration", json("PUT", { communityKey: community.key, selectedDates, needsAccommodation: housing, displayName: name, city, confirmAttendanceChanges })); }
  async function submit() { setBusy(true); setError(undefined); try { await save(); telegram.success("Регистрация сохранена"); done(); } catch (e) { if (e instanceof ApiError && e.code === "registration_dates_affect_gatherings" && e.affectedGatherings?.length) { const summary = e.affectedGatherings.map(x => `• ${x.gameName}, ${new Date(x.startsAtUtc).toLocaleString("ru-RU", { dateStyle: "long", timeStyle: "short" })}`).join("\n"); if (await telegram.confirm(`Вы больше не сможете участвовать в этих сборах и будете выведены из состава:\n${summary}\n\nПродолжить?`)) { try { await save(true); telegram.success("Регистрация и составы сборов обновлены"); done(); return; } catch (retry) { setError(retry instanceof Error ? retry.message : String(retry)); } } } else setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  async function unregister() { if (!await telegram.confirm("Отменить регистрацию?\n\nБудут удалены ваши игры и обещания привезти их. Вы выйдете из будущих сборов, а история прошедших сборов сохранится.")) return; setBusy(true); setError(undefined); try { await api("/camp/registration/unregister", json("POST", { communityKey: community.key })); telegram.success("Регистрация отменена"); done(); } catch (e) { if (e instanceof ApiError && e.code === "registration_organizer_conflict" && e.affectedGatherings?.length) setError(`Сначала отмените свои будущие сборы:\n${e.affectedGatherings.map(item => `• ${item.gameName} · ${new Date(item.startsAtUtc).toLocaleString("ru-RU", { dateStyle: "long", timeStyle: "short" })}`).join("\n")}`); else setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <Page title={state.registration?.registered ? "Редактировать регистрацию" : "Регистрация на кэмп"} subtitle={`${formatDate(state.startDate)} — ${formatDate(state.endDate)}`} actions={cancel && <button onClick={cancel}>Назад</button>}><Card className="form-grid"><Field label="Имя для участников"><input value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Из какого вы города?" hint="Город увидят только участники этого кэмпа"><input required maxLength={100} value={city} onChange={e => setCity(e.target.value)} placeholder="Например, Астана" /></Field><fieldset><legend>Когда вы будете на кэмпе?</legend><p className="muted">Отметьте фактические даты. Создавать сборы и записываться можно только на выбранные дни.</p>{state.availableDates.map(date => <label className="check" key={date}><input type="checkbox" checked={selectedDates.includes(date)} onChange={() => setSelectedDates(current => current.includes(date) ? current.filter(x => x !== date) : [...current, date].sort())} />{new Date(`${date}T00:00:00`).toLocaleDateString("ru-RU", { weekday: "short", day: "numeric", month: "long" })}</label>)}</fieldset><label className="check"><input type="checkbox" checked={housing} onChange={e => setHousing(e.target.checked)} />Нужно жильё</label>{error && <Notice kind="danger"><span className="pre-line">{error}</span></Notice>}<button className="primary" disabled={busy || !city.trim() || selectedDates.length === 0 || state.campStatus !== "Active"} onClick={submit}>{busy ? "Сохраняем…" : state.registration?.registered ? "Сохранить изменения" : "Зарегистрироваться"}</button></Card>{state.registration?.registered && <Card className="danger-zone"><h2>Отмена регистрации</h2><p>Ваши игры и обещания привезти их будут удалены, а места в будущих сборах освободятся. История сохранится.</p><button className="danger ghost" disabled={busy} onClick={unregister}>Отменить регистрацию</button></Card>}</Page>;
}

function Contributions({ community, bggAvailable, registration, editRegistration }: { community: Community; bggAvailable: boolean; registration?: RegistrationState; editRegistration: () => void }) {
  const state = useAsync(() => api<Contribution[]>(`/camp/contributions?community=${encodeURIComponent(community.key)}`), [community.key]);
  const storageKey = `oyinq-camp-import-${community.key}`;
  const [importId, setImportId] = useState<string | undefined>(() => new URLSearchParams(location.search).get("import") ?? localStorage.getItem(storageKey) ?? undefined); const [chosen, setChosen] = useState<ClubGame>(); const [selectedExpansions, setSelectedExpansions] = useState<number[]>([]); const [listQuery, setListQuery] = useState(""); const [adding, setAdding] = useState(false); const [error, setError] = useState<string>();
  const visibleContributions = useMemo(() => {
    const values = state.data ?? [];
    if (!listQuery.trim()) return values;
    const ids = new Set(searchGames(values.map(item => ({ bggId: item.bggId, ...item.snapshot, expansions: [] })), listQuery).map(game => game.bggId));
    return values.filter(item => ids.has(item.bggId));
  }, [state.data, listQuery]);
  useEffect(() => telegram.back(Boolean(importId), () => { localStorage.removeItem(storageKey); setImportId(undefined); state.reload(); }), [importId]);
  async function startImport(input: string) { setError(undefined); try { const result = await api<{ publicId: string }>("/camp/imports", json("POST", { communityKey: community.key, bggInput: input })); localStorage.setItem(storageKey, result.publicId); setImportId(result.publicId); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function addManual() { if (!chosen) return; setAdding(true); setError(undefined); try { await api("/camp/contributions/manual", json("POST", { communityKey: community.key, bggInput: String(chosen.bggId), expansionBggIds: selectedExpansions })); setChosen(undefined); setSelectedExpansions([]); telegram.success("Игра и данные BGG добавлены"); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setAdding(false); } }
  async function remove(item: Contribution) { if (!await telegram.confirm(`Убрать «${item.snapshot.name}» из ваших игр этого кэмпа?\n\nДругие участники больше не будут видеть вас как владельца этой копии.`)) return; setError(undefined); try { await api(`/camp/contributions/${item.itemType}/${item.bggId}?community=${encodeURIComponent(community.key)}`, { method: "DELETE" }); telegram.success("Игра удалена"); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function commitment(item: Contribution) { const next = item.commitment === "Bringing" ? "Available" : "Bringing"; setError(undefined); try { await api(`/camp/contributions/${item.itemType}/${item.bggId}/commitment`, json("PUT", { communityKey: community.key, commitment: next })); telegram.success(next === "Bringing" ? "Вы точно привезёте игру" : "Обещание снято"); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  if (importId) return <ImportProgress community={community} id={importId} close={() => { localStorage.removeItem(storageKey); setImportId(undefined); state.reload(); }} />;
  const duplicateInBase = Boolean(chosen && registration?.baseGameIds.includes(chosen.bggId));
  return <Page title="Мои игры" actions={<button onClick={editRegistration}>Редактировать регистрацию</button>}>
    {!bggAvailable && <Notice kind="warning">BGG временно недоступен. Сохранённые игры можно просматривать, отмечать и удалять.</Notice>}
    <section className="page-section"><h2>Добавить игры</h2><Card><h3>Импортировать коллекцию BGG</h3><p className="muted">Импортирует вашу коллекцию и позволит выбрать, что вы сможете привезти на кэмп.</p><BggImportButton available={bggAvailable} start={startImport} /></Card><div className="section-divider"><span>или</span></div>
    <Card><h3>Добавить одну игру</h3><GamePicker bggAvailable={bggAvailable} selected={chosen} label="Найдите игру по названию или BGG-ссылке"
      onSelect={game => { setChosen(game); setSelectedExpansions([]); }}
      onClear={() => { setChosen(undefined); setSelectedExpansions([]); }} />
      {chosen && <div className="selected-game"><div className="media"><Cover src={chosen.thumbnailImageUrl} name={chosen.name} /><div><h3>{chosen.name}</h3><GameMeta game={chosen} /></div></div>{duplicateInBase && <Notice kind="warning">Эта игра уже доступна в базовой коллекции кэмпа. Личную копию можно добавить только явно при разборе импорта BGG.</Notice>}{chosen.expansions.length > 0 && <fieldset><legend>Дополнения, которые вы можете привезти</legend>{chosen.expansions.map(expansion => <label className="check" key={expansion.bggId}><input type="checkbox" checked={selectedExpansions.includes(expansion.bggId)} onChange={() => setSelectedExpansions(current => current.includes(expansion.bggId) ? current.filter(id => id !== expansion.bggId) : [...current, expansion.bggId])} />{expansion.name}</label>)}</fieldset>}<button className="primary" disabled={adding || duplicateInBase} onClick={addManual}>{adding ? "Добавляем…" : "Добавить в мои игры"}</button></div>}
    </Card></section>
    <section className="page-section"><h2>Ваши игры</h2>{error && <Notice kind="danger">{error}</Notice>}{state.loading ? <Loading /> : state.error ? <ErrorState message={state.error} retry={state.reload} /> : !state.data?.length ? <Empty>Вы пока не добавили игры. Импортируйте коллекцию BGG или добавьте одну игру.</Empty> : <><Field label="Поиск среди добавленных игр"><input type="search" value={listQuery} onChange={event => setListQuery(event.target.value)} placeholder="Название игры" /></Field>{!visibleContributions.length ? <Empty>Ничего не найдено. Попробуйте сократить запрос.</Empty> : <div className="stack">{visibleContributions.map(item => <Card key={`${item.itemType}-${item.bggId}`}><div className="row contribution-row"><div className="media"><Cover src={item.snapshot.thumbnailImageUrl} name={item.snapshot.name} /><div><h2>{item.snapshot.name}</h2><Badge tone={item.commitment === "Bringing" ? "success" : "neutral"}>{item.commitment === "Bringing" ? "Точно привезу" : "Могу привезти"}</Badge>{item.itemType === "Expansion" && <span className="muted"> Дополнение</span>}<GameMeta game={{ bggId: item.bggId, ...item.snapshot, expansions: [] }} /></div></div><div className="row"><button onClick={() => commitment(item)}>{item.commitment === "Bringing" ? "Снять обещание" : "Точно привезу"}</button><button className="danger ghost" onClick={() => remove(item)}>Убрать</button></div></div></Card>)}</div>}</>}</section>
  </Page>;
}

function BggImportButton({ available, start }: { available: boolean; start: (input: string) => void }) {
  const [open, setOpen] = useState(false); const [input, setInput] = useState("");
  return open ? <><Field label="Профиль BoardGameGeek" hint="Имя пользователя или ссылка на профиль"><input value={input} onChange={e => setInput(e.target.value)} placeholder="Например, John90" /></Field><button className="primary" disabled={!available || !input.trim()} onClick={() => start(input)}>Импортировать коллекцию</button></> : <button className="primary" disabled={!available} onClick={() => setOpen(true)}>Импортировать коллекцию</button>;
}

function ImportProgress({ community, id, close }: { community: Community; id: string; close: () => void }) {
  const state = useAsync(() => api<CampImport>(`/camp/imports/${id}?community=${encodeURIComponent(community.key)}`), [community.key, id]);
  const [actionError, setActionError] = useState<string>();
  useEffect(() => { if (!state.data || ["Queued", "Running"].includes(state.data.status)) { const timer = window.setInterval(state.reload, 3000); return () => clearInterval(timer); } }, [state.data?.status, state.reload]);
  async function cancel() { if (!await telegram.confirm("Отменить импорт? Выбранные игры не будут сохранены.")) return; setActionError(undefined); try { await api(`/camp/imports/${id}/cancel`, json("POST", { communityKey: community.key })); telegram.success("Импорт отменён"); close(); } catch (e) { setActionError(e instanceof Error ? e.message : String(e)); } }
  if (state.loading && !state.data) return <Page title="Импорт BGG"><Loading label="BGG готовит коллекцию. Можно закрыть и вернуться позже." /></Page>;
  if (state.error) return <Page title="Импорт BGG" actions={<button onClick={close}>Закрыть</button>}><ErrorState message={state.error} retry={state.reload} /></Page>;
  if (!state.data) return null;
  if (state.data.status === "Failed") return <Page title="Импорт BGG"><Notice kind="danger">Не удалось импортировать коллекцию BGG. Сохранённые игры не изменены; попробуйте ещё раз позже.</Notice><button onClick={() => api(`/camp/imports/${id}/retry`, json("POST", { communityKey: community.key })).then(state.reload)}>Повторить</button><button onClick={close}>К моим играм</button></Page>;
  if (state.data.status === "Cancelled") return <Page title="Импорт отменён"><Notice>Черновик не был применён.</Notice><button onClick={close}>К моим играм</button></Page>;
  if (state.data.status !== "Completed" && state.data.status !== "Confirmed") return <Page title="Импорт BGG" subtitle={state.data.progressTotal ? `Этап ${state.data.progressCurrent} из ${state.data.progressTotal}` : "В очереди"}><Loading label="Импорт выполняется в фоне. Эту страницу можно закрыть." />{actionError && <Notice kind="danger">{actionError}</Notice>}<div className="row"><button onClick={close}>Продолжить позже</button><button className="danger ghost" onClick={cancel}>Отменить импорт</button></div></Page>;
  if (state.data.status === "Confirmed") { const overridable = state.data.draft?.items.filter(item => item.skipReason === "AlreadyInBaseCollection" && item.isOverridable) ?? []; return <Page title="Импорт завершён"><Notice kind="success">Выбранные игры сохранены.</Notice>{state.data.hasSelectedOverridableItems && !state.data.overrideResolution && <BaseDuplicateResolution community={community} id={id} count={overridable.length} done={state.reload} />}{state.data.overrideResolution && <Notice>{state.data.overrideResolution === "AddPersonalCopies" ? "Ваши личные копии добавлены." : "Игры остаются только в базовой коллекции кэмпа."}</Notice>}<button onClick={close}>К моим играм</button></Page>; }
  return <ImportSelection community={community} id={id} items={state.data.draft?.items ?? []} done={close} cancel={cancel} cancellationError={actionError} />;
}

function ImportSelection({ community, id, items, done, cancel, cancellationError }: { community: Community; id: string; items: ImportDraftItem[]; done: () => void; cancel: () => void; cancellationError?: string }) {
  const [selected, setSelected] = useState(() => defaultImportSelection(items));
  const [query, setQuery] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const isExpansion = (item: ImportDraftItem) => item.itemType === "Expansion";
  const normalizedQuery = query.trim().toLowerCase();
  const expansions = useMemo(() => items.filter(isExpansion), [items]);
  const parentIds = (item: ImportDraftItem) => item.parentBggIds?.length ? item.parentBggIds : item.parentBggId ? [item.parentBggId] : [];
  const bases = useMemo(() => items.filter(x => !isExpansion(x) && (!normalizedQuery || x.snapshot.name.toLowerCase().includes(normalizedQuery) || expansions.some(exp => exp.parentBggId === x.bggId && exp.snapshot.name.toLowerCase().includes(normalizedQuery)))), [items, expansions, normalizedQuery]);
  const orphans = useMemo(() => expansions.filter(exp => !items.some(base => !isExpansion(base) && parentIds(exp).includes(base.bggId)) && (!normalizedQuery || exp.snapshot.name.toLowerCase().includes(normalizedQuery))), [items, expansions, normalizedQuery]);
  const toggle = (item: ImportDraftItem) => setSelected(current => { const next = new Set(current); const key = importItemKey(item); next.has(key) ? next.delete(key) : next.add(key); return next; });
  const hasBase = (item: ImportDraftItem) => parentIds(item).length === 0 || items.some(base => !isExpansion(base) && parentIds(item).includes(base.bggId) && selected.has(`${base.itemType}-${base.bggId}`));
  const selectable = isImportItemSelectable;
  async function confirm() { setBusy(true); try { await api(`/camp/imports/${id}/confirm`, json("POST", { communityKey: community.key, selectedBaseGameIds: items.filter(x => !isExpansion(x) && selected.has(`${x.itemType}-${x.bggId}`)).map(x => x.bggId), selectedExpansionIds: items.filter(x => isExpansion(x) && selected.has(`${x.itemType}-${x.bggId}`)).map(x => x.bggId) })); telegram.success("Игры добавлены"); done(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  const hasMatches = bases.length > 0 || orphans.length > 0;
  return <Page title="Выберите игры" subtitle={`Выбрано ${selected.size} из ${items.length}`} actions={<button className="danger ghost" onClick={cancel}>Отменить импорт</button>}><div className="row"><button onClick={() => setSelected(new Set(items.filter(selectable).map(x => `${x.itemType}-${x.bggId}`)))}>Выбрать всё доступное</button><button onClick={() => setSelected(new Set())}>Очистить</button></div><Field label="Поиск"><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Игра или дополнение" /></Field>{!hasMatches ? <Empty>Ничего не найдено.</Empty> : <div className="import-groups">{bases.map(base => { const children = expansions.filter(x => parentIds(x).includes(base.bggId) && (!normalizedQuery || base.snapshot.name.toLowerCase().includes(normalizedQuery) || x.snapshot.name.toLowerCase().includes(normalizedQuery))); return <details open={normalizedQuery ? true : undefined} key={base.bggId}><summary><label className="check"><input type="checkbox" disabled={!selectable(base)} checked={selected.has(`${base.itemType}-${base.bggId}`)} onChange={() => toggle(base)} /><ImportItemSummary item={base} /></label></summary>{children.map(exp => <label className={`check nested ${selected.has(`${exp.itemType}-${exp.bggId}`) && !hasBase(exp) ? "missing-base" : ""}`} key={exp.bggId}><input type="checkbox" disabled={!selectable(exp)} checked={selected.has(`${exp.itemType}-${exp.bggId}`)} onChange={() => toggle(exp)} /><ImportItemSummary item={exp} />{selected.has(`${exp.itemType}-${exp.bggId}`) && !hasBase(exp) && <span className="missing-base-note">Нет базовой игры</span>}</label>)}</details>; })}{orphans.length > 0 && <section className="notice warning"><strong>Дополнения без базовой игры</strong><p className="muted">Это допустимо: их можно привезти отдельно.</p>{orphans.map(exp => <label className={`check nested ${selected.has(`${exp.itemType}-${exp.bggId}`) ? "missing-base" : ""}`} key={exp.bggId}><input type="checkbox" disabled={!selectable(exp)} checked={selected.has(`${exp.itemType}-${exp.bggId}`)} onChange={() => toggle(exp)} /><ImportItemSummary item={exp} />{selected.has(`${exp.itemType}-${exp.bggId}`) && <span className="missing-base-note">Базовой игры нет в вашей коллекции</span>}</label>)}</section>}</div>}{(error || cancellationError) && <Notice kind="danger">{error ?? cancellationError}</Notice>}<button className="primary sticky-action" disabled={busy} onClick={confirm}>{busy ? "Сохраняем…" : `Сохранить (${selected.size})`}</button></Page>;
}

function ImportItemSummary({ item }: { item: ImportDraftItem }) {
  const reason = item.skipReason === "AlreadyInBaseCollection" ? "Уже есть в базовой коллекции" : item.skipReason === "AlreadyAddedManually" ? "Уже добавлено вручную" : item.skipReason ? "Не удалось добавить" : undefined;
  return <span className="import-item-summary"><Cover src={item.snapshot.thumbnailImageUrl} name={item.snapshot.name} /><span><strong>{item.snapshot.name}</strong>{reason && <small>{reason}</small>}<GameMeta game={{ bggId: item.bggId, ...item.snapshot, expansions: [] }} compact /></span></span>;
}

function BaseDuplicateResolution({ community, id, count, done }: { community: Community; id: string; count: number; done: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  async function resolve(resolution: "KeepBaseCollection" | "AddPersonalCopies") { setBusy(true); setError(undefined); try { await api(`/camp/imports/${id}/resolve-base-duplicates`, json("POST", { communityKey: community.key, resolution })); telegram.success(resolution === "AddPersonalCopies" ? "Личные копии добавлены" : "Оставлено без изменений"); done(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } }
  return <Card className="form-grid"><h2>Игры уже есть в кэмпе</h2><p>{count} игр уже доступны из базовой коллекции. Личная копия обычно не нужна, но вы можете зарегистрировать её отдельно.</p><div className="row"><button disabled={busy} onClick={() => resolve("KeepBaseCollection")}>Оставить как есть</button><button className="primary" disabled={busy} onClick={() => resolve("AddPersonalCopies")}>Добавить мои копии</button></div>{error && <Notice kind="danger">{error}</Notice>}</Card>;
}
